#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define WINDOW_HEIGHT 1000
#define WINDOW_WIDTH 1900

#define PROGRAM_NAME "MyGame"

#define MAIN_SCREEN_RATIO 0.7
#define TILING_SCREEN_HORIZONTAL_RATIO 0.9

#endif //CONFIGURATION_H